@startuml

title __ENTITIES's Class Diagram__\n

  namespace de.gematik.ti.openhealthcard.events.response.entities {
    class de.gematik.ti.openhealthcard.events.response.entities.CardAccessNumber {
        - value : String
        + CardAccessNumber()
        + getValue()
    }
  }
  

  namespace de.gematik.ti.openhealthcard.events.response.entities {
    class de.gematik.ti.openhealthcard.events.response.entities.PaceKey {
        - enc : byte[]
        - mac : byte[]
        + PaceKey()
        + getEnc()
        + getMac()
    }
  }
  

  namespace de.gematik.ti.openhealthcard.events.response.entities {
    class de.gematik.ti.openhealthcard.events.response.entities.PinNumber {
        - value : String
        + PinNumber()
        + getPinType()
        + getValue()
    }
  }
  

  namespace de.gematik.ti.openhealthcard.events.response.entities {
    class de.gematik.ti.openhealthcard.events.response.entities.PinResult {
        {static} - LOG : Logger
        - errorTextByFailure : String
        - numberRemain : int
        - pinVerifiSuccess : boolean
        - warningText : String
        + PinResult()
        + getErrorTextByFailure()
        + getNumberRemain()
        + getWarningText()
        + isPinVerifiSuccess()
        + setNumberRemain()
        + setPinVerifiSuccess()
    }
  }
  

  de.gematik.ti.openhealthcard.events.response.entities.PinNumber o-- de.gematik.ti.openhealthcard.events.control.PinType : pinType


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
