@startuml

title __CONTROL's Class Diagram__\n

  namespace de.gematik.ti.openhealthcard.events.control {
    class de.gematik.ti.openhealthcard.events.control.CommonEventTransmitter {
        {static} - packageFilter : String
        {static} + postError()
        {static} + postError()
        {static} + postInfo()
        {static} + postWarn()
        {static} + setPackageFilter()
        - CommonEventTransmitter()
        {static} - checkStackTraceElement()
        {static} - findClassName()
    }
  }
  

  namespace de.gematik.ti.openhealthcard.events.control {
    enum PinType {
      MRPIN_AMTS
      MRPIN_DPE
      MRPIN_DPE_READ
      MRPIN_GDD
      MRPIN_NFD
      MRPIN_NFD_READ
      MRPIN_OSE
      PIN_CH
    }
  }
  

  namespace de.gematik.ti.openhealthcard.events.control {
    class de.gematik.ti.openhealthcard.events.control.RequestTransmitter {
        + cardAccessNumber()
        + paceKey()
        + pinNumber()
        + requestCardAccessNumber()
        + requestPaceKey()
    }
  }
  

  namespace de.gematik.ti.openhealthcard.events.control {
    class de.gematik.ti.openhealthcard.events.control.RequestTransmitterCardAccessNumber {
        + request()
        + request()
        ~ RequestTransmitterCardAccessNumber()
    }
  }
  

  namespace de.gematik.ti.openhealthcard.events.control {
    class de.gematik.ti.openhealthcard.events.control.RequestTransmitterPaceKey {
        + request()
        + request()
        ~ RequestTransmitterPaceKey()
    }
  }
  

  namespace de.gematik.ti.openhealthcard.events.control {
    class de.gematik.ti.openhealthcard.events.control.RequestTransmitterPinNumber {
        + RequestTransmitterPinNumber()
        + request()
        + request()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
